-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 10:52:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nombre_de_tu_base_de_datos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nombre_de_tu_base_de_datos` ;

-- -----------------------------------------------------
-- Schema nombre_de_tu_base_de_datos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nombre_de_tu_base_de_datos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema dashuri
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dashuri` ;

-- -----------------------------------------------------
-- Schema dashuri
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dashuri` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `nombre_de_tu_base_de_datos` ;

-- -----------------------------------------------------
-- Table `nombre_de_tu_base_de_datos`.`core_categoriaproducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nombre_de_tu_base_de_datos`.`core_categoriaproducto` ;

CREATE TABLE IF NOT EXISTS `nombre_de_tu_base_de_datos`.`core_categoriaproducto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nombre_de_tu_base_de_datos`.`detalles_reserva_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nombre_de_tu_base_de_datos`.`detalles_reserva_producto` ;

CREATE TABLE IF NOT EXISTS `nombre_de_tu_base_de_datos`.`detalles_reserva_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nombre_de_tu_base_de_datos`.`producto_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nombre_de_tu_base_de_datos`.`producto_proveedor` ;

CREATE TABLE IF NOT EXISTS `nombre_de_tu_base_de_datos`.`producto_proveedor` (
  `producto_id` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `dashuri` ;

-- -----------------------------------------------------
-- Table `dashuri`.`categoria_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`categoria_producto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`categoria_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`usuario` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `nivel` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`cita_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`cita_servicio` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`cita_servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_cita` DATE NOT NULL,
  `hora_cita` TIME NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `costo` DECIMAL(10,2) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `cita_servicio_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dashuri`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`servicios` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`servicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`cita_servicio_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`cita_servicio_detalle` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`cita_servicio_detalle` (
  `cita_id` INT NOT NULL,
  `servicio_id` INT NOT NULL,
  PRIMARY KEY (`cita_id`, `servicio_id`),
  INDEX `servicio_id` (`servicio_id` ASC) VISIBLE,
  CONSTRAINT `cita_servicio_detalle_ibfk_1`
    FOREIGN KEY (`cita_id`)
    REFERENCES `dashuri`.`cita_servicio` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `cita_servicio_detalle_ibfk_2`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `dashuri`.`servicios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`compra` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `proveedor_id` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `dashuri`.`proveedor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`producto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `categoria_id` INT NOT NULL,
  `fecha_exp` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dashuri`.`categoria_producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`detalles_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`detalles_compra` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`detalles_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `sub_total` DECIMAL(10,2) NOT NULL,
  `detalles` TEXT NULL DEFAULT NULL,
  `fecha_compra` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_id` (`compra_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `detalles_compra_ibfk_1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `dashuri`.`compra` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `detalles_compra_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`venta` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dashuri`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`detalles_reserva_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`detalles_reserva_producto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`detalles_reserva_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `venta_id` (`venta_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `detalles_reserva_producto_ibfk_1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `dashuri`.`venta` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `detalles_reserva_producto_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`producto_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`producto_proveedor` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`producto_proveedor` (
  `producto_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`producto_id`, `proveedor_id`),
  INDEX `proveedor_id` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `producto_proveedor_ibfk_1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`producto` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `producto_proveedor_ibfk_2`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `dashuri`.`proveedor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`registro_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`registro_cliente` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`registro_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `registro_cliente_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dashuri`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
