-- MySQL Script generated by MySQL Workbench
-- Sun Mar 30 12:44:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dashuri
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dashuri` ;

-- -----------------------------------------------------
-- Schema dashuri
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dashuri` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventario` ;

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dashuri` ;

-- -----------------------------------------------------
-- Table `dashuri`.`auth_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`auth_group` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`django_content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`django_content_type` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`auth_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`auth_permission` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `dashuri`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`auth_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`auth_group_permissions` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`auth_group_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `dashuri`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `dashuri`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`auth_user` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`auth_user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`auth_user_groups` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`auth_user_groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `dashuri`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `dashuri`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`auth_user_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`auth_user_user_permissions` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`auth_user_user_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `dashuri`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `dashuri`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`categoria_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`categoria_producto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`categoria_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`cliente` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`cita_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`cita_servicio` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`cita_servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_cita` DATE NOT NULL,
  `hora_cita` TIME NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `costo` DECIMAL(10,2) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `cita_servicio_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `dashuri`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`servicios` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`servicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`cita_servicio_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`cita_servicio_detalle` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`cita_servicio_detalle` (
  `cita_id` INT NOT NULL,
  `servicio_id` INT NOT NULL,
  PRIMARY KEY (`cita_id`, `servicio_id`),
  INDEX `servicio_id` (`servicio_id` ASC) VISIBLE,
  CONSTRAINT `cita_servicio_detalle_ibfk_1`
    FOREIGN KEY (`cita_id`)
    REFERENCES `dashuri`.`cita_servicio` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `cita_servicio_detalle_ibfk_2`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `dashuri`.`servicios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`compra` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `proveedor_id` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `dashuri`.`proveedor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_categoriaproducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_categoriaproducto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_categoriaproducto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_cliente` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_cliente` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_proveedor` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_proveedor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_compra` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_compra` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `proveedor_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `core_compra_proveedor_id_ccbd056a_fk_core_proveedor_id` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `core_compra_proveedor_id_ccbd056a_fk_core_proveedor_id`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `dashuri`.`core_proveedor` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_producto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_producto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `core_producto_categoria_id_65b2d0af_fk_core_categoriaproducto_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `core_producto_categoria_id_65b2d0af_fk_core_categoriaproducto_id`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dashuri`.`core_categoriaproducto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_detallescompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_detallescompra` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_detallescompra` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `sub_total` DECIMAL(10,2) NOT NULL,
  `detalles` LONGTEXT NULL DEFAULT NULL,
  `compra_id` BIGINT NOT NULL,
  `producto_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `core_detallescompra_compra_id_21582107_fk_core_compra_id` (`compra_id` ASC) VISIBLE,
  INDEX `core_detallescompra_producto_id_c3bc5abd_fk_core_producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `core_detallescompra_compra_id_21582107_fk_core_compra_id`
    FOREIGN KEY (`compra_id`)
    REFERENCES `dashuri`.`core_compra` (`id`),
  CONSTRAINT `core_detallescompra_producto_id_c3bc5abd_fk_core_producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`core_producto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_facturareserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_facturareserva` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_facturareserva` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(10,2) NOT NULL,
  `cliente_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `core_facturareserva_cliente_id_8198eb0d_fk_core_cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `core_facturareserva_cliente_id_8198eb0d_fk_core_cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `dashuri`.`core_cliente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_detallesreservaproducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_detallesreservaproducto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_detallesreservaproducto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `factura_id` BIGINT NOT NULL,
  `producto_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `core_detallesreserva_factura_id_06af002a_fk_core_fact` (`factura_id` ASC) VISIBLE,
  INDEX `core_detallesreserva_producto_id_e54e383c_fk_core_prod` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `core_detallesreserva_factura_id_06af002a_fk_core_fact`
    FOREIGN KEY (`factura_id`)
    REFERENCES `dashuri`.`core_facturareserva` (`id`),
  CONSTRAINT `core_detallesreserva_producto_id_e54e383c_fk_core_prod`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`core_producto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`core_productoproveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`core_productoproveedor` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`core_productoproveedor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `producto_id` BIGINT NOT NULL,
  `proveedor_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `core_productoproveedor_producto_id_56bfdb49_fk_core_producto_id` (`producto_id` ASC) VISIBLE,
  INDEX `core_productoproveed_proveedor_id_322a9b1e_fk_core_prov` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `core_productoproveed_proveedor_id_322a9b1e_fk_core_prov`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `dashuri`.`core_proveedor` (`id`),
  CONSTRAINT `core_productoproveedor_producto_id_56bfdb49_fk_core_producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`core_producto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`producto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dashuri`.`categoria_producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`detalles_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`detalles_compra` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`detalles_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `sub_total` DECIMAL(10,2) NOT NULL,
  `detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_id` (`compra_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `detalles_compra_ibfk_1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `dashuri`.`compra` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `detalles_compra_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`venta` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `dashuri`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`detalles_reserva_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`detalles_reserva_producto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`detalles_reserva_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `venta_id` (`venta_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `detalles_reserva_producto_ibfk_1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `dashuri`.`venta` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `detalles_reserva_producto_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`django_admin_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`django_admin_log` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `dashuri`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `dashuri`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`django_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`django_migrations` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`django_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`django_session` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`producto_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`producto_proveedor` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`producto_proveedor` (
  `producto_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`producto_id`, `proveedor_id`),
  INDEX `proveedor_id` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `producto_proveedor_ibfk_1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `dashuri`.`producto` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `producto_proveedor_ibfk_2`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `dashuri`.`proveedor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dashuri`.`ventas_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashuri`.`ventas_producto` ;

CREATE TABLE IF NOT EXISTS `dashuri`.`ventas_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_detalles_reserva_prod` INT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_detalles_reserva_prod` (`id_detalles_reserva_prod` ASC) VISIBLE,
  CONSTRAINT `ventas_producto_ibfk_1`
    FOREIGN KEY (`id_detalles_reserva_prod`)
    REFERENCES `dashuri`.`detalles_reserva_producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`administrador` ;

CREATE TABLE IF NOT EXISTS `inventario`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`categoria_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`categoria_producto` ;

CREATE TABLE IF NOT EXISTS `inventario`.`categoria_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`cliente` ;

CREATE TABLE IF NOT EXISTS `inventario`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`cita_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`cita_servicio` ;

CREATE TABLE IF NOT EXISTS `inventario`.`cita_servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_cita` DATE NOT NULL,
  `hora_cita` TIME NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `costo` DECIMAL(10,2) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `cita_servicio_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `inventario`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`servicios` ;

CREATE TABLE IF NOT EXISTS `inventario`.`servicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`cita_servicio_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`cita_servicio_detalle` ;

CREATE TABLE IF NOT EXISTS `inventario`.`cita_servicio_detalle` (
  `cita_id` INT NOT NULL,
  `servicio_id` INT NOT NULL,
  PRIMARY KEY (`cita_id`, `servicio_id`),
  INDEX `servicio_id` (`servicio_id` ASC) VISIBLE,
  CONSTRAINT `cita_servicio_detalle_ibfk_1`
    FOREIGN KEY (`cita_id`)
    REFERENCES `inventario`.`cita_servicio` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `cita_servicio_detalle_ibfk_2`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `inventario`.`servicios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `inventario`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`compra` ;

CREATE TABLE IF NOT EXISTS `inventario`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `proveedor_id` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `inventario`.`proveedor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`producto` ;

CREATE TABLE IF NOT EXISTS `inventario`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `inventario`.`categoria_producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`detalles_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`detalles_compra` ;

CREATE TABLE IF NOT EXISTS `inventario`.`detalles_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `sub_total` DECIMAL(10,2) NOT NULL,
  `detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_id` (`compra_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `detalles_compra_ibfk_1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `inventario`.`compra` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `detalles_compra_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `inventario`.`producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`venta` ;

CREATE TABLE IF NOT EXISTS `inventario`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `inventario`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`detalles_reserva_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`detalles_reserva_producto` ;

CREATE TABLE IF NOT EXISTS `inventario`.`detalles_reserva_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `venta_id` (`venta_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `detalles_reserva_producto_ibfk_1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `inventario`.`venta` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `detalles_reserva_producto_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `inventario`.`producto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`producto_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`producto_proveedor` ;

CREATE TABLE IF NOT EXISTS `inventario`.`producto_proveedor` (
  `producto_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`producto_id`, `proveedor_id`),
  INDEX `proveedor_id` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `producto_proveedor_ibfk_1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `inventario`.`producto` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `producto_proveedor_ibfk_2`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `inventario`.`proveedor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`registro_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`registro_cliente` ;

CREATE TABLE IF NOT EXISTS `inventario`.`registro_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `registro_cliente_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `inventario`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
